-- MySQL Script generated by MySQL Workbench
-- Tue Feb 25 17:44:33 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Location`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Location` (
  `idLocation` INT NOT NULL,
  `Street` VARCHAR(255) NULL,
  `City` VARCHAR(255) NULL,
  `Zipcode` VARCHAR(16) NULL,
  `latitude` VARCHAR(45) NULL,
  `longitude` VARCHAR(45) NULL,
  PRIMARY KEY (`idLocation`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`BankInfo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`BankInfo` (
  `idBankInfo` INT NOT NULL,
  `BankName` VARCHAR(255) NULL COMMENT 'Bank name',
  `AccountNo` VARCHAR(16) NULL,
  `RoutingNo` VARCHAR(16) NULL,
  `AccName` VARCHAR(255) NULL COMMENT 'Account name',
  PRIMARY KEY (`idBankInfo`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Business`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Business` (
  `idBusiness` INT NOT NULL auto_increment COMMENT 'Auto increment ID for business',
  `email` VARCHAR(255) NOT NULL COMMENT 'email - primary key for login',
  `password` VARCHAR(32) NOT NULL COMMENT 'Password from 6-32 character',
  `BName` VARCHAR(255) NULL COMMENT 'Business name',
  `Blocation` INT NOT NULL COMMENT 'Business location',
  `OName` VARCHAR(255) NULL COMMENT 'Owner name',
  `OSSN` CHAR(11) NULL COMMENT 'Owner Social Security Number',
  `BankAccount` INT NULL,
  UNIQUE INDEX `BID_UNIQUE` (`idBusiness` ASC) VISIBLE,
  PRIMARY KEY (`idBusiness`),
  INDEX `loc_idx` (`Blocation` ASC) VISIBLE,
  INDEX `bank_idx` (`BankAccount` ASC) VISIBLE,
  CONSTRAINT `loc`
    FOREIGN KEY (`Blocation`)
    REFERENCES `mydb`.`Location` (`idLocation`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `bank`
    FOREIGN KEY (`BankAccount`)
    REFERENCES `mydb`.`BankInfo` (`idBankInfo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `mydb`.`Driver`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Driver` (
  `idDriver` INT NOT NULL auto_increment COMMENT 'Driver ID - auto generate when create',
  `email` VARCHAR(255) NOT NULL COMMENT 'driver email to log in',
  `password` VARCHAR(255) NOT NULL COMMENT 'Driver password to log in',
  `DName` VARCHAR(255) NOT NULL COMMENT 'Driver name',
  `Dlocation` INT NULL,
  `DSSN` VARCHAR(45) NULL,
  `Drivercol` VARCHAR(45) NULL COMMENT 'Driver Social Security Number',
  `BankAccount` INT NULL,
  UNIQUE INDEX `idDriver_UNIQUE` (`idDriver` ASC) VISIBLE,
  PRIMARY KEY (`idDriver`),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) VISIBLE,
  UNIQUE INDEX `Drivercol_UNIQUE` (`Drivercol` ASC) VISIBLE,
  INDEX `loc_idx` (`Dlocation` ASC) VISIBLE,
  INDEX `bank_idx` (`BankAccount` ASC) VISIBLE,
  CONSTRAINT `loc2`
    FOREIGN KEY (`Dlocation`)
    REFERENCES `mydb`.`Location` (`idLocation`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `bank2`
    FOREIGN KEY (`BankAccount`)
    REFERENCES `mydb`.`BankInfo` (`idBankInfo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Request`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Request` (
  `idRequest` INT NOT NULL auto_increment,
  `BID` INT NULL,
  `DID` INT NULL,
  `StartLoc` VARCHAR(255) NULL,
  `EndLoc` VARCHAR(255) NULL,
  `RequestTime` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  `PickupTime` DATETIME NULL,
  `EndTime` DATETIME NULL,
  `Route` FLOAT NULL,
  `Cost` FLOAT NULL,
  `Status` VARCHAR(255) NULL,
  PRIMARY KEY (`idRequest`),
  UNIQUE INDEX `idRequest_UNIQUE` (`idRequest` ASC) VISIBLE,
  INDEX `BID_idx` (`BID` ASC) VISIBLE,
  INDEX `DID_idx` (`DID` ASC) VISIBLE,
  CONSTRAINT `BID`
    FOREIGN KEY (`BID`)
    REFERENCES `mydb`.`Business` (`idBusiness`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `DID`
    FOREIGN KEY (`DID`)
    REFERENCES `mydb`.`Driver` (`idDriver`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
